### ISSUE TITLE
Audio Convertor

### ISSUE THREAD

**Issue by AmirAzizi** [lecode-official/ffmpeg-dotnet#3]
Hi,
I have to convert .amr file to .oga or .ogg file in .netcore
I want to use this library but I dont know how ... (I was added this dll correctly)
would you please help me :(
that is so important :((
please ... :(((
I'm sorry for my weak English language :)

**Comment by lecode-official** [comment]
Hi Amir,

I am really sorry, this project is no longer being maintained. But if you have an idea how to solve this problem in C or C++, then looking at my code, it should be rather simple to implement this conversion yourself. Since I won't be addressing this issue, I am going to close it. Feel free to post your solution if you found one.

Cheers,
David
